import file_IO_helper as fio

def get_all_states(i = 0, folder = "states", partial = False, reduced_only = False, same = True):
    '''This function produces the automaton generated by graphs in folder "states". It saves
    the generated states in folder "states."
    Set partial = True to allow partial folds.
    Set reduced_only = True to only allow graphs wihtout separating edges
    Set same = False to prohibit same-length folds.
    '''
    while fio.graph_file(i, folder) != fio.next_graph(folder):
        print(i)
        graph = fio.read_graph(i, folder)
        print("These are the nodes of the graph we are folding:")
        graph.print_nodes()
         graph.perform_legal_folds(folder, partial, reduced_only, same)
        fio.write_graph(graph, i, folder)
        i += 1
    print("Finished!")

if __name__ == "__main__":
    #get_all_states(folder = "rank_4", partial = False, reduced_only = False, same = False)
    return
            
